services:
  web:
    build:
      context: .
      dockerfile: Docker-multistage-file
    image: fruitable-app:latest
    container_name: fruitable-new-cont
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
