# Generated by Django 5.2 on 2025-05-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_delete_add_to_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='p_id',
            new_name='product_id',
        ),
    ]
