# Generated by Django 5.2 on 2025-05-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_p_id_cart_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Add_to_cart',
        ),
    ]
