# Generated by Django 5.2 on 2025-05-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_cart_add_to_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='total',
            new_name='total_price',
        ),
    ]
