# Generated by Django 5.2 on 2025-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
