# Generated by Django 5.2 on 2025-07-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_coupon_user_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Coupon_code',
            new_name='coupon_code',
        ),
    ]
